Etatcivil/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from ajax_select import urls as ajax_select_urls
from gestciv import views

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'', include(('gestciv.urls', 'gestciv'), namespace='gestciv')),
    url(r'^gestciv', include(('gestciv.urls', 'gestciv'), namespace='gestciv')),
    url(r'^gestciv/ajax_lookups/', include(ajax_select_urls)),
]

gestciv/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from gestciv import ajax
from gestciv import views 
import pdfkit

appName="gestciv"
urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login'),

    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^home$', views.HomeView.as_view(), name='home'),
    url(r'birth/save_father_form_to_session/(?P<dest_url>\S+)/$', views.save_father_form_to_session, name='save_father_form_to_session'),
    url(r'birth/save_mother_form_to_session/(?P<dest_url>\S+)/$', views.save_mother_form_to_session, name='save_mother_form_to_session'),
    url(r'birth/search_for_new_birth/(?P<dest_url>\S+)/$', views.search_for_new_birth, name='search_for_new_birth'),


#########################################################"
#
# Partie configuration
#
##########################################################
    url(r'departement/add/$', views.DepCreateView.as_view(), name='dept_add'),



#########################################################


    url(r'birthdeclare/search_for_new_birth/(?P<dest_url>\S+)/$', views.search_for_new_birth, name='search_for_new_birth'),
    url(r'birthdeclare/nbadd/$', views.BirthDeclarationCreateView.as_view(), name='nbirth_add'),
    url(r'birthdeclare/nbadd/(?P<nip>\w+)$', views.BirthDeclarationCreateView.as_view(), name='nbirth_add'),
    url(r'birthdeclare/list/$', views.BirthDeclarationListView.as_view(), name='nbirth_list'),
    url(r'birthdeclare/list/(?P<display>\w+)/$', views.BirthDeclarationListView.as_view(), name='nbirth_list'),
    url(r'birthdeclararation/(?P<pk>\d+)/$', views.BirthDeclarationUpdateView.as_view(), name='nbirth_update'),

    url(r'birth/add/(?P<from_external_page>\w+)?$', views.BirthCreateView.as_view(), name='birth_add'),
    url(r'birth/(?P<pk>\d+)/delete/$', views.BirthDeleteView.as_view(), name='birth_delete'),
    url(r'birth/add/(?P<pk>\d+)/$', views.BirthFormUniqueNumber, name='birth_add'),
    url(r'birth/certificate/import/$', views.BirthDeclarationImportView.as_view(), name='birth_declaration_import'),
    url(r'birth/genpdf/(?P<birth_id>\d+)$', views.gen_acte_naissance, name='gen_ec_pdf'),
#    url(r'birth/genpdf/(?P<birth_id>\d+)$', views.gen_possession_etat_pdf, name='gen_pe_pdf'),
    url(r'birth/list/$', views.BirthListView.as_view(), name='birth_list'),
    url(r'birth/list/(?P<nip>\w+)/$', views.BirthListView.as_view(), name='birth_list'),
    url(r'birth/list/(?P<nip>\w+)/$', views.BirthListView.as_view(), name='birth_list'),
    url(r'birth/(?P<pk>\d+)/$', views.BirthUpdateView.as_view(), name='birth_update'),


    url(r'death/declaration/$', views.DeathDeclarationView.as_view(), name='death_declaration'),
#    url(r'birth/genpdf/(?P<birth_id>\d+)$', views.gen_acte_naissance, name='gen_ec_pdf'),
#    url(r'birth/genpdf/(?P<birth_id>\d+)$', views.gen_possession_etat_pdf, name='gen_pe_pdf'),
#    url(r'birth/list/$', views.BirthListView.as_view(), name='birth_list'),
#    url(r'birth/list/(?P<nip>\w+)/$', views.BirthListView.as_view(), name='birth_list'),
#    url(r'birth/list/(?P<nip>\w+)/$', views.BirthListView.as_view(), name='birth_list'),
#    url(r'birth/(?P<pk>\d+)/$', views.BirthUpdateView.as_view(), name='birth_update'),


    url(r'registration/add/(?P<redirect_to_birth>\w+)?$', views.RegistrationCreateView.as_view(), name='registration_add'),
    url(r'registration/update/(?P<pk>\d+)/$', views.RegistrationUpdateView.as_view(), name='registration_update'),
#    url(r'registration/update/(?P<pk>\d+)/$', views.RegistrationUpdateView.as_view(), name='registration_update'),
    url(r'registration/delete/(?P<pk>\d+)/delete/$', views.RegistrationDeleteView.as_view(), name='registration_delete'),
    url(r'registration/list/$', views.RegistrationListView.as_view(), name='registration_list'),
    url(r'registration/genpepdf/(?P<registration_id>\d+)$', views.gen_possession_etat_pdf, name='gen_pe_pdf'),
    url(r'registration/genarpdf/(?P<registration_id>\d+)$', views.gen_attestation_residence_pdf, name='gen_ar_pdf'),
    url(r'ajax/get/get_mairie_arrondissement/?$', ajax.get_mairie_arrondissement, name='get_mairie_arrondissement'),
    url(r'ajax/get/get_default_arrondissement/?$', ajax.get_default_arrondissement, name='get_default_arrondissement'),
    url(r'ajax/get/get_arrondissement_quartier/?$', ajax.get_arrondissement_quartier, name='get_arrondissement_quartier'),
    url(r'ajax/get/get_default_arrondissement/?$', ajax.get_default_arrondissement, name='get_default_arrondissement'),
    url(r'statistics/registration/$', views.StatisticsRegistrationView.as_view(), name='statistics_registration'),
    url(r'statistics/birth/$', views.StatisticsBirthView.as_view(), name='statistics_birth'),

    url(r'death/add/$', views.DeathCreateView.as_view(), name='death_add'),
]

gestciv/models.py
from django.urls import reverse_lazy, reverse
from django.db import models
from datetime import datetime, timedelta, date
from django_countries.fields import CountryField
from django.forms import ModelChoiceField, ModelForm
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext
from random import randint
from django.contrib.auth.models import User as DjangoUser
from django.contrib.auth.models import Group as DjangoGroup
from django.db.models import Q
from django.contrib.auth.models import User, Group, Permission
from django.db.models.signals import post_save
from django.dispatch import receiver
from geodivision.models import GroupeEthnique,Arrondissement,Mairie,Quartier
from django.conf import settings
import string
import uuid

STATUS_CHOICES=(
	('C','Célibataire'),
	('M','Marié'),
	('V','Veuf'),
        ('I','Décédé'),
        ('D','Divorcé'))

CIVILITY_CHOICES=(
	('M.', 'M.'),
	('MME', 'Mme')
	)

SEX_CHOICES=(
	('M','Masculin'),
	('F', 'Féminin')
	)

BIRTH_TYPE=(
	('Simple','Simple'),
	('Jumeau','Jumeau'),
	('Triplé','Triplé'),
	('Quadruplé','Quadruplé'),
	('Autre','Autre'))


class GeneralConfiguration(models.Model):
    appli_name = models.TextField(verbose_name=_("Software name"), default=u"Eregister")
    default_country = CountryField(verbose_name=_("Default country"), default="BJ")
    nav_history = models.PositiveSmallIntegerField(_("Navigation history"), default=10)

    def __str__(self):
        return ugettext("Configuration")  # TODO: check if it could be lazy

    class Meta:
        verbose_name = _("Global settings of the software")
        verbose_name_plural = verbose_name



class UserNavigationHistoryManager(models.Manager):
    def get_list(self, user):
        return self.filter(accessed_by=user).order_by('accessed_by')


class UserNavigationHistory(models.Model):
    NAV_HISTORY = 10

    accessed_by = models.ForeignKey(DjangoUser, related_name='accede_par', on_delete=models.CASCADE)
    accessed_on = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=80)
    url = models.CharField(max_length=255)

    objects = UserNavigationHistoryManager()

    @staticmethod
    def add(url, title, user):
        lst = UserNavigationHistory.objects.get_list(user)
        h = UserNavigationHistory(url=url, title=title, accessed_by=user)
        h.save()

    @staticmethod
    def exist_url(url):
        return UserNavigationHistory.objects.filter(url=url).count() > 0

#############


class ReferenceEntity(models.Model):
    label = models.CharField(u"Description", max_length=30)

    class Meta:
        abstract = True

    def __str__(self):
        return self.label


#########
# Model #
#########

class ModelEntity(models.Model):
    created_by = models.ForeignKey(DjangoUser, related_name="%(app_label)s_%(class)s_add", on_delete=models.PROTECT, null=True, blank=True)
    created_on = models.DateTimeField(verbose_name=u"Créé le", auto_now_add=True)
    modified_by = models.ForeignKey(DjangoUser, related_name="%(app_label)s_%(class)s_update", null=True, blank=True, on_delete=models.PROTECT)
    modified_on = models.DateTimeField(verbose_name=u"Modifié le", auto_now=True, null=True, blank=True)

    def clean(self):
        super(ModelEntity, self).clean()

    def save(self, *args, **kwargs):
        super(ModelEntity, self).save(*args, **kwargs)

    class Meta:
       abstract = True


class Language(ReferenceEntity):
    is_default = models.BooleanField(_("Default language"), default=False)

    class Meta:
        verbose_name = _("Language")
        verbose_name_plural = _("Languages")

    @staticmethod
    def get_default_language():
        if Language.objects.count() > 0:
            return Language.objects.filter(is_default=True)[0]
        else:
            return None




################################################
#
# Fonction de création d'un groupe à partir 
# d'un signal reçu lors de la  création d'une commune 
# ou d'un arrondissement
#######################################################
def CreateGroup(sender, instance, **kwargs):
	new_group = instance
	if kwargs["created"]:
		new_group, created = Group.objects.get_or_create(name=new_group)


class Profession(models.Model):
	code            = models.DecimalField(max_digits=4,  decimal_places=0, verbose_name="Code")
	nom             = models.CharField(max_length=50, null=False, unique=True, verbose_name='Profession')


	def __str__(self):
		return self.nom

	class Meta:
		ordering = ['nom']
		verbose_name = _("Profession")
		verbose_name_plural = _("Professions")



#######################################################################
#
# Définition d'un profil utilisateur spécifique à ce projet
#
########################################################################
class UserProfile(models.Model):
	user		=	models.OneToOneField(User, related_name='User', on_delete=models.CASCADE)
	photo		=	models.FileField(verbose_name=("Photo de profile"),upload_to='static/', 
						max_length=255, null=True, blank=True)
	profession	=	models.CharField(default='', max_length=50, blank=True)
	phone		=	models.CharField(default='', max_length=10, blank=True)
	organization	=	models.CharField(default='', max_length=10, verbose_name='Lieu de travail', blank=True)
	city		= 	models.ForeignKey(Arrondissement, related_name='profil_ville', verbose_name='Ville',
					on_delete=models.CASCADE, null=True, blank=True)


def  CreateProfile(sender, **kwargs):
	user = kwargs["instance"]
	if kwargs["created"]:
		user_profile = UserProfile(user=user)
		user_profile.save()

post_save.connect(CreateProfile, sender=User)

######################################################################

class PublishedManager(models.Manager):

        def get_queryset(self):
                return super(PublishedManager, self).get_queryset().filter(status='published')


class RegistrationManager(models.Manager):
    def get_by_first_and_last_name(self, firstname, lastname, birthday):
        return self.filter(firstname__iexact=firstname, lastname__iexact=lastname).first()


    def search(self, nip='', name=''):
        r_list = self.all()
        if nip != '':
            r_list  = r_list.filter(nip__istartswith = nip)
        if name != '':
            r_list = r_list.filter(Q(lastname__istartswith=name) | Q(firstname__istartswith=name) )
        return r_list

    def is_single(self):
       if self.objects.search(self.nip).filter(status = 'C') is not None:
          return "Célibataire"
       return "Marié"


class Registration(ModelEntity):


	STREET_TYPE_CHOICES = (
		('Boulevard', 'Boulevard'),
		('Avenue', 'Avenue'),
		('Cours', 'Cours'),
		('Place', 'Place'),
		('Rue', 'Rue'),
		('Route', 'Route'),
		('Voie', 'Voie'),
		('Chemin', 'Chemin'),
		('Square', 'Square'),
		('Impasse', 'Impasse'),
		('Rond-point', 'Rond-point'),
		('Quai', 'Quai')
	)



	nip 		            = models.CharField(max_length=30, null=True, blank=True, verbose_name='Numéro identifiant privé')
	title                       = models.CharField(max_length=3, choices=CIVILITY_CHOICES, default='M.', verbose_name="Civilité")
	lastname                    = models.CharField(max_length=255, verbose_name='Nom')
	young_girl_lastname         = models.CharField(max_length=30, verbose_name='Nom de jeune fille', blank=True)
	firstname                   = models.CharField(max_length=255, verbose_name='Prénom')
	ice	                    = models.ForeignKey("self", related_name='ice_registration', verbose_name='Personne à joindre', 
					on_delete=models.CASCADE, null=True, blank=True)
	status                      = models.CharField(max_length=15, choices=STATUS_CHOICES, default='M',verbose_name='Stuation')
	sex                         = models.CharField(max_length=8, choices=SEX_CHOICES, 
                                            default='F', null=True, blank=True, verbose_name='Sexe')
	birthday                    = models.DateField(verbose_name='Date de naissance')
	nationality                 = CountryField(max_length=255, verbose_name='Pays de naissance', default="BJ")
	job                         = models.ForeignKey(Profession, related_name='profession_reg', 
						on_delete=models.CASCADE, verbose_name='Profession')
	father_name		    = models.CharField(max_length=255, verbose_name='Nom/Prénom du père', null=True, blank=True)
	mother_name		    = models.CharField(max_length=255, verbose_name='Nom/Prénom de la mère', null=True, blank=True)
	ethnie 			    =  models.ForeignKey(GroupeEthnique, related_name='ethnie_reside', 
                                        null=True, blank=True, verbose_name='Ethnie', on_delete=models.CASCADE)
	arrived_date                = models.DateField(verbose_name='Date d\'arrivée', null=True, blank=True)
	city	       		    =  models.ForeignKey(Mairie, related_name='mairie_reside', null=True, blank=True, verbose_name='Commune', 
						on_delete=models.CASCADE)
	district                    = models.ForeignKey(Arrondissement, related_name='arron_reside', null=True, blank=True, 
						verbose_name='Arrondissement', on_delete=models.CASCADE)
	neighborhood                    = models.ForeignKey(Quartier, related_name='neighbor_reside', null=True, blank=True,
						 verbose_name='Quartier', on_delete=models.CASCADE)
	street_type 		    = models.CharField(max_length=30, verbose_name="Type de rue", null=True, blank=True,
					   choices=STREET_TYPE_CHOICES, default='Rue')
	comp_1 			    = models.CharField(max_length=255, verbose_name="Complément 1", blank=True, null=True)
	comp_2 			    = models.CharField(max_length=255, verbose_name="Complément 2", blank=True, null=True)
	dead			    = models.BooleanField(default=False, null=True, blank=True)
	phone                       = models.CharField(max_length=255, blank=True, null=True, verbose_name='Téléphone')
	mail                        = models.EmailField(max_length=255, verbose_name='Mail', blank=True, null=True)

gestciv/templates/gestciv/_inc_form_edit_buttons_std.html
{% load i18n %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        {% if form.instance.id > 0 and delete_url %}
            <a class="btn btn-danger" href="{% url delete_url form.instance.id %}">{% trans "Delete" %}</a>
        {% endif %}
    </div>
</div>

gestciv/templates/gestciv/_inc_form_edit_content_std.html
{% load tag_extras %}

{% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label {{ field.css_classes }}">{{ field.label }}</label>
        <div class="col-sm-10">
            {{ field|addcss:"form-control" }}
            {% if field.errors %}
                <div class="text-danger">{{ field.errors }}</div>
            {% endif %}
        </div>
    </div>
{% endfor %}

gestciv/templates/gestciv/acte_de_naissance.html
{% extends 'gestciv/base_tpl.html' %}
{% load i18n %}

{% block title %}{{ TOWN_HALL }}{% endblock %}

{% block pageTitle %}{% trans "Extrat d'acte de naissane de " %} {{ birth.firstname }} {{ birth.father.lastname }} {% endblock %}

{% block content %}



		<div class="pub">EXTRAIT DU REGISTRE DE L'ETAT CIVIL</div> 
		<div class="volet"> <h4>Volet N <sup>o</sup>1 (A remettre au d&eacute;clarant) </h4> </div>
		<div class="extrait">EXTRAIT D'ACTE DE NAISSANCE</div>
		<div class="mairie">Mairie de Calavi</div>
		
		
		<div class="cote" >
			R&eacute;publique du B&eacute;nin <br/>
			<div style=margin-top:5px>D&eacute;partement {{birth.departement }} </div> 
			<div style=margin-top:4px>Commune de {{birth.commune }} <div/><br/>
		</div>
		
		
		
		<div>
			<div id="bloc">		
				Je soussign&eacute;(e): {{birth.arrondissement.responsable }} <br/>
				Fonction : {{birth.arrondissement.titre }}<br/>
				Certifie avoir re&ccedil;u la d&eacute;claration de naissance de<br/>
				Pr&eacute;nom de l'enfant: {{birth.firstname }} <br/>
				Sexe : {{birth.sex }} <br/>
				 
				<div style=margin-top:17px;><b>P&egrave;re</b></div>
				Nom : {{birth.father.lastname }} <br/>
				Prénoms : {{birth.father.firstname }}<br/>
				Né le: {{birth.father.birthday }}<br/>
				Profession: {{birth.father.job }} <br/>
				Domicile: {{birth.father.address }} {{birth.father.city }} <br/>
				 
				<div style=margin-top:17px;><b>M&egrave;re</b></div>
				Nom : {{birth.mother.lastname }} <br/>
				Pr&eacute;noms M&egrave;re: {{birth.mother.firstname }} <br/>
				Né le: {{birth.mother.birthday }}     <br/>
				Profession: {{birth.mother.job }}   <br/>
				Domicile : {{birth.mother.address }} {{birth.mother.city }} <br/>
				 
				<div style=margin-top:17px;><b>D&eacute;clarant</b></div>
				Nom : <br/>
				Prénom :<br/>
				Âge :  <br/>
				Profession :  <br/>
				Domicile :  <br/>
				 
				 
				 
				<div style=margin-left:12%;>
					Date et heure de la naissance: <br/>
					Lieu de la naissance   <br/>
					Date de la d&eacute;claration  <br/>
				</div>
				 
			</div>
				<br/>
			<div style=margin-left:0px;>
			Copie conforme au.... <br/>
				Cotonou le
			</div>
					<div class="conc">
                    Signature et cachet de l'officier de l'état civil
					</div>
		</div>
{% endblock %}







gestciv/templates/gestciv/base_tpl.html
{% load i18n %}
{% load static %}
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Etat Civil">
        <meta name="author" content="YAYI Olabiyi Patrick">
        <!--link rel="icon" href="../../favicon.ico" -->
      
        <title>{% block title %}Idadu Tech - {{ EREGISTER_NAME }}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'gestciv/layout/bootstrap/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'gestciv/layout/style.css' %}" />
        <link rel="stylesheet" href="{% static 'gestciv/layout/font-awesome/css/all.min.css' %}">
        {% block head %}{% endblock %}
    </head>

    <body>
        <div class="container">
            <!-- Static navbar -->
            <div class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">{% trans "Toggle navigation" %}</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'gestciv:home' %}">{% trans "Home" %}</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Maternité<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'gestciv:nbirth_add' %}">{% trans "Déclaration de naissance" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_declaration_import' %}">{% trans "Importer une déclaration" %}</a></li>
                                    <li><a href="{% url 'gestciv:nbirth_list' %}">{% trans "Liste des naissances" %}</a></li>
                            <!--        <li><a href="{% url 'gestciv:nbirth_list' 'late' %}">{% trans "Mariage" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_add' 'late' %}">{% trans "Divorce" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_list' 'current' %}">{% trans "Décès" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_list' %}">{% trans "Enfant sans vie" %}</a></li>
                                    <li><a href="{% url 'gestciv:nbirth_list' %}">{% trans "Recherche naissance" %}</a></li> -->
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Les actes" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'gestciv:birth_list' %}">{% trans "Acte de mariage" %}</a></li>
                                    <li><a href="{% url 'gestciv:death_add' %}">{% trans "Declaration de décès" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_list' %}">{% trans "Acte de naissance" %}</a></li>
                                    <li><a href="{% url 'gestciv:death_declaration' %}">{% trans "Acte de décès" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_list' %}">{% trans "Autorisation parentale" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_list' %}">{% trans "Livret de famille" %}</a></li>
                                </ul>
                            </li>
                        </ul>
			<ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Vie du quartier" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'gestciv:registration_add' %}">{% trans "Enregistrer administrté" %}</a></li>
                                    <li><a href="{% url 'gestciv:registration_list' %}">{% trans "Recherche administrté" %}</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Statistiques" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'gestciv:statistics_birth' %}">{% trans "Tables annuelles" %}</a></li>
                                    <li><a href="{% url 'gestciv:statistics_registration' %}">{% trans "Tables décennales" %}</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Configuration" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'gestciv:dept_add' %}">{% trans "Département" %}</a></li>
                                    <li><a href="{% url 'gestciv:birth_list' %}">{% trans "Liste des paramètres" %}</a></li>
                                </ul>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                            {% if user.is_authenticated %}
                                <a href="{% url 'gestciv:logout' %}">{% trans "Log out" %} {{ user.first_name }}</a>
                            {% else %}
                                <a href="{% url 'gestciv:login' %}">{% trans "Log in" %}</a>
                            {% endif %}
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/admin">{% trans "Administration" %}</a></li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "History" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    {% for item in request.session.user_nav_list %}
                                        <li><a href="{{ item.0 }}">{{ item.1 }}</a></li>
                                     {% empty %}
                                        <li>{% trans "Empty" %}</li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </div>
          
            <div class="container">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% block pageTitle %}Etat Civil{% endblock %}</h3>
                    </div>
                    <div class="panel-body">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div><!-- /.container -->
        <div align="center">
            Idadu Tech - Licence GNU GPLv3 - {{ VERSION|safe }} - {{ LIBRARY_NAME }}
        </div>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'gestciv/layout/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'gestciv/layout/bootstrap/js/bootstrap.min.js' %}"></script>
        {% block jscript %}{% endblock %}
    </body>
</html>

gestciv/templates/gestciv/login.html
{% extends 'gestciv/base_tpl.html' %}
{% load i18n %}

{% block title %}{% trans "Authentication" %}{% endblock %}

{% block pageTitle %}{% trans "Authentication" %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm-12">
        {% include 'gestciv/_inc_form_edit_header.html' %}
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "Login" %}</h2>
            </div>
            <div class="panel-body">
                <form id="login_form" method="post" action="{% url 'gestciv:login' %}">{% csrf_token %}
                    <div class="form-group">
                        <div class="row">
                            <label for="username" class="col-sm-2 control-label">{% trans "Username" %}</label>
                            <div class="col-sm-10">
                                <input id="username" type="text" name="username" value="" size="20" />
                            </div>
                        </div>
                        <div class="row">
                            <label for="password" class="col-sm-2 control-label">{% trans "Password" %}</label>
                            <div class="col-sm-10">
                                <input id="password" type="password" name="password" value="" size="20" />
                            </div>
                        </div>
                    </div>        
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">{% trans "Log in" %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div><!-- /.col-sm-12 -->
</div>
{% endblock %}